### ISSUE TITLE
Weapon skinning model

### ISSUE THREAD

**Issue by 909919898** [cryotb/R5R_AimAssist_Forcer#4]
Can I learn from you about the weapon skinning model of the R5 S3 version? I encountered a bottleneck when trying to make it myself.How can I contact you？

**Comment by cryotb** [comment]
Hi,

I'm afraid to tell you that your issue does not seem to be related at all to this repository, which means i will not be able to make any further comments on this discussion. I will thus lock your issue as it contains content that isn't related to R5R_AAF in any way. Aforementioned fact invalidates any requirement for further discussion on this issue tracker.

Now, to not leave your question entirely unanswered: I'd recommend you to check out how the game determines and enforces the model index of your weapons. R5Reloaded is a free game with no protections whatsoever, i.e you can freely debug it. Just play around and rack up some hours in form of time spent on playing around with things. You will find multiple methods to achieve what you want, each with their own caveats.

Best of luck with your R5Reloaded adventures man, i kind of gave up on that game. 
 
Regards
cryotB
